spring.application.name=fifa-account-drops

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=user
spring.datasource.password=password

browser.headless=false
browser.timeout.default=30000
browser.timeout.queue=600000

accounts.persistence.enabled=true

nst.host=localhost
nst.port=8000
nst.url=http://${nst.host}:${nst.port}/api/v2
nst.api-key=2b95d0f1-e96c-4e65-9e7d-d2b80b9e4770
nst.group-id=56c06302-be10-4253-b919-ad4085070d1b

threads.count=1

proxy=rp.scrapegw.com:6060:lc8ih8r74hue5hj-country-us-session-wgwqfyqzjt-lifetime-5:21iikh90yjyglec