spring.application.name=fifa-account-drops

spring.profiles.active=server

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user
spring.datasource.password=password

captcha.key=04e39810e2325737817e05fc08ef0126

browser.headless=false
browser.timeout.default=60000
browser.timeout.queue=300000

nst.url=http://${nst.host}:${nst.port}/api/v2
nst.api-key=2b95d0f1-e96c-4e65-9e7d-d2b80b9e4770
nst.group-id=56c06302-be10-4253-b919-ad4085070d1b

threads.count=1

accounts.persistence.enabled=true

app.proxies.enabled=false
app.proxies=geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-emTMUeFJ_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-OuWo6JZE_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-i5eBVmgR_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-QI1xf6OT_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-RnhMAmEy_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-D7n8LZBR_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-BE46v8Ag_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-KsQVhI1F_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-1NvxZXRR_lifetime-5m,geo.iproyal.com:12321:R5yjMiyIvLt0wTBo:kQY3ob1z72NgYB35_country-us_city-abbeville_session-qeLfwWY2_lifetime-5m,package-331393-country-us-sessionid-xl8gnvGRkr58zqTM-sessionlength-300:GgmsW2oeY7AWvz6I@proxy.soax.com:5000,package-331393-country-us:GgmsW2oeY7AWvz6I@proxy.soax.com:5000,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9000,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9001,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9002,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9003,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9004,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9005,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9006,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9007,GgmsW2oeY7AWvz6I:wifi;us;@proxy.soax.com:9008