spring.application.name=fifa-account-drops

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/db
spring.datasource.username=user
spring.datasource.password=password

fifa.drops.limit=1
fifa.drops.startFrom=0

browser.headless=false
browser.timeout.default=30000

nst.url=http://localhost:8848/api/v2
nst.host=localhost
nst.port=8848
nst.api-key=2b95d0f1-e96c-4e65-9e7d-d2b80b9e4770
nst.group-id=980aad55-f13c-4ca6-a256-0537b3dbf710

threads.count=1