version: "3.9"

services:
  accounts_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  accounts-nstbrowserless:
    image: nstbrowser/browserless:143-202601221200.v3
    container_name: nstbrowserless
    environment:
      TOKEN: ${NST_TOKEN}
      VNC_PORT: ${VNC_PORT}
      VNC_PASSWORD: ${VNC_PASSWORD}
      CHROME_ARGS: >
        --disable-blink-features=AutomationControlled
        --disable-infobars
        --disable-web-security
        --disable-features=site-per-process
        --start-maximized
        --no-sandbox
    ports:
      - "${NST_PORT}:8848"
      - "${VNC_PORT}:6900"
    restart: unless-stopped

  fifa-account-drop-app:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - accounts_db
      - accounts-nstbrowserless

volumes:
  pgdata: