version: "3.9"

services:
  accounts_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "7194:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  accounts-nstbrowserless:
    image: nstbrowser/browserless:143-202601221200.v3
    container_name: nstbrowserless
    environment:
      TOKEN: ${NST_TOKEN}
      VNC_PORT: 6461
      VNC_PASSWORD: 1234
      CHROME_ARGS: >
        --disable-blink-features=AutomationControlled
        --disable-infobars
        --disable-web-security
        --disable-features=site-per-process
        --start-maximized
        --no-sandbox
    ports:
      - "9593:8848"
      - "6461:6900"
    restart: unless-stopped

volumes:
  pgdata: